stages:
  - "build"

build-backend:
  stage: "build"
  image:
    name: 'gcr.io/kaniko-project/executor:debug'
    entrypoint: [""]
  script:
    - echo "DATABASE_URL=\"${PWD}\"" > .env
    - echo "BASE_URL='https://eps-dev.net'" >> .env
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"registry01.eps-dev.de\":{\"auth\":\"$(printf "%s:%s" "${PRIVATE_REG_USER}" "${PRIVATE_REG_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
    - >-
      /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "registry01.eps-dev.de/gitlab/shortener/${CI_COMMIT_REF_SLUG}:${CI_COMMIT_SHA}"
      --destination "registry01.eps-dev.de/gitlab/shortener/${CI_COMMIT_REF_SLUG}:latest"
